name: pkgbuild

on:
  repository_dispatch:
    types:
      - rebase
  workflow_dispatch:
  push:
    branches:
      - master
      - main

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pkgbuild:
    name: pkgbuild for ${{ matrix.archlinux_arch }} for ${{ matrix.branch }}
    strategy:
      matrix:
        branch: [stable, testing, unstable]
        runs-on: [buildjet-4vcpu-ubuntu-2204-arm]
    runs-on: ${{ matrix.runs-on }}
    container:
      image: docker://manjarolinux/build:latest
    steps:
      - name: check out repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - id: version
        uses: manjaro-contrib/action-pkgbuild-info@main
      - name: pkgbuild
        uses: manjaro-contrib/action-makepkg@main
        with:
          branch: ${{ matrix.branch }}
          release: ${{ matrix.branch }}-${{ steps.version.outputs.version }}
          dispatch-target: ${{ vars.PACKAGES_REPO }}
          dispatch-token: ${{ secrets.DISPATCH_TOKEN }}
          gpg_secret_base64: ${{ secrets.gpg_secret_base64 }}
          additional_gpg: ${{ vars.ADDITIONAL_GPG }}
          additional_repo: ${{ vars.ADDITIONAL_REPO }}
