name: resubmit the release

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 1-23/2 * * *'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  resubmit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable, testing, unstable]
    steps:
      - id: version
        run: |
          echo "VERSION=$(gh release list --limit 3 | grep "${{ matrix.branch }}" | head -1 | awk '{print $1;}')" >> $GITHUB_ENV
      - name: dispatch
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # v2
        with:
          token: ${{ secrets.DISPATCH }}
          repository: manjaro-sway/packages
          event-type: package_update
          client-payload: '{ "repository": "${{ github.repository }}", "version": "${{ env.VERSION }}" }'
